runtime: python39
entrypoint: gunicorn -b :$PORT api_predict:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  SUPABASE_URL: ${SUPABASE_URL}
  SUPABASE_KEY: ${SUPABASE_KEY}
  SUPABASE_BUCKET: ${SUPABASE_BUCKET}
  GOOGLE_API_KEY: ""

requirements.txt: requirements.txt

handlers:
- url: /.*
  script: auto
  secure: always 