runtime: python39
entrypoint: gunicorn -b :$PORT api_predict:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  SUPABASE_URL: ""
  SUPABASE_KEY: ""
  SUPABASE_BUCKET: ""
  GOOGLE_API_KEY: ""

requirements.txt: requirements.txt 